name: fairness
channels:
- defaults
- conda-forge
dependencies:
- tensorflow=2.10.0
- fairlearn=0.8.0
- seaborn=0.12.2
- ipykernel=6.15.0
- mkl_fft=1.3.1
- mkl_random=1.2.2
- scikit-lego=0.6.14
- aif360=0.3.0
- pip=22.3.1
- matplotlib=3.6.2
- scikit-learn=1.2.0
- pandas=1.5.2
- numpy=1.23.5
- scipy=1.9.3